
namespace Arch.ILS.EconomicModel
{
    public class Submission
    {
        public int SubmissionId { get; set; }
        public int ProgramId { get; set; }
        public string RegisId { get; set; }
        public string BaseCurrency { get; set; }
        public string Currency { get; set; }
        public decimal FXRate { get; set; }
        public DateTime FXDate { get; set; }
        public TranType TranType { get; set; }
        public DateTime InceptionDefault { get; set; }
        public int UWYearDefault { get; set; }
        public bool IsMultiyear { get; set; }
        public bool IsCancellable { get; set; }
        //public DateTime ExpirationDefault { get; set; }
        //public DateTime? QuoteDeadline { get; set; }
        //public DateTime? AuthDeadline { get; set; }
        //public DateTime? Arrived { get; set; }
        //public int BrokerId { get; set; }
        //public int? BrokerContactId { get; set; }
        //public int UnderwriterId { get; set; }
        //public int? ActuaryId { get; set; }
        //public int? AnalystId { get; set; }
        //public int? ModelerId { get; set; }
        //public int? RiskZoneId { get; set; }
        //public string Notes { get; set; }
        //public string UWNotes { get; set; }
        //public string Correspondence { get; set; }
        //public string StrategicNotes { get; set; }
        //public string RefId { get; set; }
        //public int Status { get; set; }
        //public bool IsRenewal { get; set; }
        //public int DocStatus { get; set; }
        //public int ModelingStatus { get; set; }
        //public string Priority { get; set; }
        //public int? ExpiringSubmissionId { get; set; }
        //public decimal Surplus { get; set; }
        //public int ClientScore { get; set; }
        //public int SubmissionWriteupId { get; set; }
        //public DateTime CreateDate { get; set; }
        //public string CreateUser { get; set; }
        //public DateTime ModifyDate { get; set; }
        //public string ModifyUser { get; set; }
        //public bool IsActive { get; set; }
        //public bool IsDeleted { get; set; }
        //public int? LegalTermsId { get; set; }
        //public int PlacementYear { get; set; }
        //public int? ParentSubmissionId { get; set; }
        //public string CedentAltName { get; set; }
        //public DateTime? ModelingDeadline { get; set; }
        //public string ModelingNotes { get; set; }
        //public string DataLinkNotes { get; set; }
        //public DateTime? MdlStatusDate { get; set; }
        //public string ActuarialNotes { get; set; }
        //public int? RelshipUnderwriterId { get; set; }
        //public decimal? MarketShare { get; set; }
        //public DateTime? CorreAuthDeadline { get; set; }
        //public int CorreStatus { get; set; }
        //public int ActuarialStatus { get; set; }
        //public string SubmissionDataLinkNotes { get; set; }
        //public string ActuarialDataLinkNotes { get; set; }
        //public DateTime? ActuarialDeadline { get; set; }
        //public string Source { get; set; }
        //public bool IsCorreInterest { get; set; }
        //public string ActuarialPriority { get; set; }
        //public int RegisSyncStatus { get; set; }
        //public int? LastRegisSyncByUserId { get; set; }
        //public DateTime? LastRegisSyncDate { get; set; }
        //public int ModelingComplexity { get; set; }
        //public string ActuarialDataCheck { get; set; }
        //public string ActuarialRanking { get; set; }
        //public bool IsActuarialDataCheckRequested { get; set; }
        public long RowVersion { get; set; }
        //public int ERCLossViewArch { get; set; }
        //public int ERCLossViewAir { get; set; }
        //public int ERCLossViewRMS { get; set; }
        //public decimal? FxRateSBFUSD { get; set; }
        //public decimal? FxRateSBFGBP { get; set; }
        //public DateTime? FxDateSBF { get; set; }
        //public string IrisPolicyNumber { get; set; }
        //public string RationaleQuote { get; set; }
        //public string RationaleAuth { get; set; }
        //public string RationaleSigned { get; set; }
        //public DateTime? IrisSLA { get; set; }
        //public bool IsCollateralized { get; set; }
        //public int BrokerRating { get; set; }
        //public string BrokerRationale { get; set; }
        //public int PNOCDays { get; set; }
        //public int ClientAdvocacyRating { get; set; }
        //public string ClientAdvocacyRationale { get; set; }
        //public string LMXIndicator { get; set; }
        //public int? ActuaryPeerReviewerId { get; set; }
        //public string ClientAdvocacyLink { get; set; }
        //public int? GroupBuyerId { get; set; }
        //public int? LocalBuyerId { get; set; }
        //public bool IsActuaryPeerReviewNotRequired { get; set; }
        //public int CedeCoverageSelectionType { get; set; }
        //public int DataScoreRating { get; set; }
    }
}
