
namespace Arch.ILS.EconomicModel.Historical
{
    public class ScenarioLayer
    {
        public long ScenarioId { get; set; }
        public int LayerId { get; set; }
        //public string RegisMKey { get; set; }
        //public int SubmissionId { get; set; }
        //public int LayerNum { get; set; }
        //public int SubLayerNum { get; set; }
        //public int ReinstCount { get; set; }
        public decimal Placement { get; set; }
        public decimal OccLimit { get; set; }
        public decimal OccRetention { get; set; }
        //public decimal CascadeRetention { get; set; }
        //public decimal AAD { get; set; }
        public decimal AggLimit { get; set; }
        public decimal AggRetention { get; set; }
        public decimal Franchise { get; set; }
        public decimal FranchiseReverse { get; set; }
        public decimal RiskLimit { get; set; }
        public DateTime Inception { get; set; }
        //public int UWYear { get; set; }
        public DateTime Expiration { get; set; }
        //public DateTime? ExpirationFinal { get; set; }
        //public string Facility { get; set; }
        //public string Segment { get; set; }
        //public string LOB { get; set; }
        //public int ContractType { get; set; }
        public int LimitBasis { get; set; }
        //public int AttachBasis { get; set; }
        //public int LAETerm { get; set; }
        //public decimal ROL { get; set; }
        //public decimal QuoteROL { get; set; }
        //public decimal EstimatedShare { get; set; }
        //public decimal SignedShare { get; set; }
        //public decimal AuthShare { get; set; }
        //public decimal QuotedShare { get; set; }
        //public int Status { get; set; }
        //public string LayerDesc { get; set; }
        //public string Notes { get; set; }
        //public decimal Rate { get; set; }
        //public int PremiumFreq { get; set; }
        //public int LayerType { get; set; }
        //public DateTime CreateDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        //public decimal InuringLimit { get; set; }
        public decimal RiskRetention { get; set; }
        //public int LayerCategory { get; set; }
        //public string LayerCatalog { get; set; }
        public decimal Premium { get; set; }
        //public decimal QuotePremium { get; set; }
        //public decimal RelShare { get; set; }
        //public decimal TargetNetShare { get; set; }
        //public decimal? BoundFXRate { get; set; }
        //public DateTime? BoundFXDate { get; set; }
        //public decimal? ERCActual { get; set; }
        //public string ERCActualSource { get; set; }
        //public decimal? ELMarketShare { get; set; }
        //public decimal? ELHistoricalBurn { get; set; }
        //public decimal? ELBroker { get; set; }
        //public int ProgramId { get; set; }
        //public string ProgramExtName { get; set; }
        //public long CedentId { get; set; }
        //public string CedentName { get; set; }
        //public long CedentGroupId { get; set; }
        //public string CedentGroupName { get; set; }
        //public long DepartmentId { get; set; }
        //public string DepartmentName { get; set; }
        //public long OfficeId { get; set; }
        //public string OfficeName { get; set; }
        //public int CompanyId { get; set; }
        //public string CompanyName { get; set; }
        //public long UnderwriterId { get; set; }
        //public string Underwriter { get; set; }
        //public string UnderwriterName { get; set; }
        //public int SubmissionTranType { get; set; }
        //public string Currency { get; set; }
        //public string LegalEntity { get; set; }
        //public DateTime? ModifiedDate { get; set; }
        //public string ModifiedBy { get; set; }
        //public decimal? ReinstPercent { get; set; }
        //public long? CompanyCode { get; set; }
        //public string RiskRegion { get; set; }
        //public string RiskZone { get; set; }
    }
}
